server:
  port: 8080

spring:
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.200.130:3306/takeout?characterEncoding=utf-8
        username: root
        password: abc123
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.200.140:3306/takeout?characterEncoding=utf-8
        username: root
        password: abc123
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    allow-bean-definition-overriding: true #允许 bean 定义范围配置项
  cache:
    type: redis
    redis:
      time-to-live: 3600000   #单位ms —— 1小时
      #      key-prefix: CACHE_      #给缓存key加前缀，不指定则分区名作为前缀
      use-key-prefix: true    #结合key-prefix，true：使用前缀
      cache-null-values: true #是否缓存空值，解决`缓存穿透`问题

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #将sql信息显示控制台
  global-config:
    db-config:
      id-type: ASSIGN_ID #主键采用雪花算法随机唯一生成

food:
  imgPath: D:\IDEA\Project_Takeout\src\main\resources\imgs\

